[package]
name = "ilagent"
version = "0.5.0"
authors = ["Chris Froehlingsdorf <chris@ilert.com>"]
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.11"
tokio = { version = "1.40", features = ["full", "rt-multi-thread"] }
actix-web = "4.9"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
json = "0.12"
reqwest = "0.12"
chrono = "0.4"
clap = "2"
ilert = "4.0.1"
uuid = { version = "1.10", features = ["v4"] }
ctrlc = { version = "3.4" }
rusqlite = { version = "0.32", features = ["bundled"] } # SQLite 3.46.0
rumqttc = "0.24"
rdkafka = { version = "0.36", features = ["cmake-build"] }
futures-util = "0.3.30"
