[package]
name = "ilagent"
version = "0.2.1"
authors = ["Chris Froehlingsdorf <cff@ilert.de>"]
edition = "2018"

[dependencies]
log = "0.4.0"
env_logger = "0.6.2"
actix-web = "1.0.7"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
json = "0.12.0"
reqwest = "0.9.20"
chrono = "0.4.9"
ctrlc = "3.1.3"
clap = "2"
ilert = "1.0.0"
uuid = { version = "0.8", features = ["v4"] }
rumqttc = "0.0.4"

[dependencies.rusqlite]
version = "0.20.0"
features = ["bundled"]