[package]
name = "ilagent"
version = "0.4.4"
authors = ["Chris Froehlingsdorf <chris@ilert.com>"]
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.10"
actix-web = "4.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
json = "0.12"
reqwest = "0.11"
chrono = "0.4"
ctrlc = "3.1"
clap = "2"
ilert = "3.2"
uuid = { version = "1.3", features = ["v4"] }
rumqttc = "0.21"

[dependencies.rusqlite]
version = "0.29" # SQLite 3.41.2
features = ["bundled"]