FROM ekidd/rust-musl-builder:1.81.0 AS builder
ADD . ./
RUN sudo chown -R rust:rust /home/rust/src
RUN cargo build --release
RUN strip /home/rust/src/target/x86_64-unknown-linux-musl/release/ilagent

FROM alpine:3.13.6 AS runner
COPY --from=builder /home/rust/src/target/x86_64-unknown-linux-musl/release/ilagent \
  /ilagent

ENTRYPOINT ["./ilagent"]